language: node_js
node_js: node
cache:
    directories:
        - node_modules
script:
    - eslint src
    - sed -i '/"homepage":/d; 2a "homepage":"'/react/$TRAVIS_BRANCH'",' package.json
    - npm run build
    - mkdir deploy
    - mv build deploy/$TRAVIS_BRANCH
deploy:
    provider: s3
    bucket: static.aryehleib.com
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    upload-dir: react
    on:
        all_branches: true
